### ISSUE TITLE
board.PlyCount is not being reset after the game ends

### ISSUE THREAD

**Issue by JoChLi** [SebLague/Chess-Challenge#119]
In the Think function i check if the PlyClount is below 2 (the first move for the bot) and if so i setup some variables. Sometimes the PlyCount doesn't get reset and those variables aren't initialized and the program crashes.  
For testing I log the PlyCount on each call to the Think function: 
```
public Move Think(Board board, Timer timer)
	{		
		Console.WriteLine(board.PlyCount);
		[...]
		return bestMove;
	}

```
![image](https://github.com/SebLague/Chess-Challenge/assets/92858191/db39933b-aab9-49b7-bef7-0a2e5a14da57)

The program crashed because PlyCount was set to 18 instead of 0

**Comment by behindcurtain3** [comment]
Having the same problem. The first game is always correct after that it may or may not be correct.

**Comment by SebLague** [comment]
The first two games are played from the starting position, but games after that are from random game positions, and the ply count includes the moves played up until that point. I realize it may have been better not to include them in the count.

Would it work to change your initialization to run once at the start of the match, instead of at the beginning of each game? In that case you could put the init code inside a constructor:
public MyBot() {
  // init code here
}

**Comment by JoChLi** [comment]
That should work. Thanks :)
