### ISSUE TITLE
pieceLists[] sometimes null when calling MovePiece

### ISSUE THREAD

**Issue by Bevan0** [SebLague/Chess-Challenge#137]
This bug occurs on line 114 of src/Framework/Chess/Board/Board.cs, in the MovePiece function. The exact exception is:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

pieceLists[] was null.
```
`pieceLists[]` is not null, but indexes 0, 7, and 8 of `pieceLists` are null. `piece` is 0, and since index 0 of `pieceLists[]` is null, it triggers this exception.

The bot thinks for about a second before the exception is triggered. My code is at [https://github.com/Bevan0/Chess-Challenge/tree/c990665ae745f6b32e99d0b80e5e4974172d4ba1](https://github.com/Bevan0/Chess-Challenge/tree/c990665ae745f6b32e99d0b80e5e4974172d4ba1)

**Comment by BillyOwen** [comment]
Me too

**Comment by SebLague** [comment]
On line 21 of MyBot you have: `if (board.IsInCheckmate()) return 100000;` This causes the function to return before it has has undone the move that you made at the start of the function. Does it work if you fix that?

**Comment by Bevan0** [comment]
That works, thanks!

**Comment by BillyOwen** [comment]
I am still getting the error sporadically, every time I make a move I also undo it.

**Comment by Bevan0** [comment]
Can you link your code?

**Comment by BillyOwen** [comment]
https://github.com/BillyOwen/Chess-Challenge/blob/main/Chess-Challenge/src/My%20Bot/MyBot.cs

**Comment by SebLague** [comment]
How sporadically are you experiencing this issue? I've run 55 games with your code so far and haven't encountered it yet.

**Comment by BillyOwen** [comment]
I only got it once :(
I think it's most likely I fixed it without realising, sorry for wasting your time

**Comment by SebLague** [comment]
No worries!

**Comment by ChickenThief** [comment]
I have gotten that error several times with several iterations of my code, but it's non-repeatable. So if I get the error in one run, I won't necessarily get it when I play on the same board with the same code. one thing I have noticed it seems to happen after timeouts. It gets a timeout, it plays an illegal move, then the code crashes. but only after some timeouts. I haven't done good investigations into this yet because it's rare and feels so random. but hopefully someone can use my anecdotal evidence to find a solution.
