### ISSUE TITLE
newBoard.MakeMove(moves[i]) gives error

### ISSUE THREAD

**Issue by The0neBoy** [SebLague/Chess-Challenge#167]
i am trying to look at all the moves the bot can do but when i make a new board variable, newBoard = board, and use newBoard.MakeMove(moves[i]) it gives me a null reference exception

**Comment by Vast342** [comment]
1: What is the context? Where is that line of code used? I can assume it's in a for loop or something based on the "i" but it would be useful to know for the people trying to help
2: If it's in a for loop did you remember to do newBoard.UndoMove(moves[i]) at the end of the loop? Otherwise, the board doesn't go back to its initial state, and most moves that get tried after that become illegal.
