### ISSUE TITLE
Can I get GetLegalMoves of single piece?

### ISSUE THREAD

**Issue by MACAYCZ** [SebLague/Chess-Challenge#18]

**Comment by WilliamAlecBrannon** [comment]
If you take a look at the documentation, and also the evilbot.cs example code, it seems like the easiest way to achieve that result would be to filter the legalmoves array in evilbot to all moves that have the same Move.StartSquare (since all moves from the same square on a position would be the same piece)

**Comment by AggregateException** [comment]
Presumably you'd want something like this:     

   Piece piece = board.GetPiece(board.GetLegalMoves()[0].StartSquare);
        Move[] pieceMoves = board.GetLegalMoves().Where((x) => x.StartSquare == piece.Square).ToArray();

**Comment by MACAYCZ** [comment]
Ok, thank you guys!
