### ISSUE TITLE
board.IsWhiteToMove appears to be working incorrectly

### ISSUE THREAD

**Issue by LukeBair** [SebLague/Chess-Challenge#218]
While working on my chess bot, I encountered a behavior that seems backward, unless I'm misunderstanding something.
The boolean variable IsWhiteToMove of the Board class returns true when my chess bot (playing as the black pieces) evaluates the position to make a move.

Does the variable IsWhiteToMove indicate the player moving _on that turn_ or does it indicate the player that is moving _on the next turn_?

**Comment by SebLague** [comment]
When you're given the board at the start of the think function, board.IsWhiteToMove will reflect whoever's turn to move it is in the actual game. However, its value will be toggled whenever you call MakeMove or UndoMove since it's now the other player's turn on your search board. Does that make sense? I've updated the docs to hopefully make this clearer.

**Comment by LukeBair** [comment]
Yes that makes sense, thanks!
