### ISSUE TITLE
How can we check memory used ? 

### ISSUE THREAD

**Issue by gagniou** [SebLague/Chess-Challenge#259]
the rules stated : 
Your bot may not use more than 256mb of memory for creating look-up tables (such as a transposition table)

i have never worked with memory limitation, so i dont know how i can check the memory my not is using. 

could anyone explain me a way to show the memory usage of the bot ?

**Comment by R0b3rt1337** [comment]
You can check the size of the datatype you are storing in your transposition / hash table using `Marshal.SizeOf<DataType>()` (Dont forget to remove it and the import before submitting since its namespace is not allowed). Once you know the size of your datatype you can calculate how many you are allowed to store using `256 * 1000 * 1000 / Marshal.SizeOf<DataType>()`. [He actually showed this in his second engine video](https://youtu.be/_vqlIPDR2TU?t=513), but using Mibibytes (1 Mibibyte = 1024 * 1024 bytes) as opposed to Megabytes (1 Megabyte = 1000 * 1000 bytes) instead which could be something @SebLague should clarify in the README.

**Comment by gagniou** [comment]
ok thank you
