### ISSUE TITLE
Is it possible to get opponent's timer?

### ISSUE THREAD

**Issue by Devil4104** [SebLague/Chess-Challenge#273]

**Comment by Pds314** [comment]
I'm not aware of a way to do this. You might be able to estimate by getting the difference in system time from three end of your last move to your current move.

**Comment by Devil4104** [comment]
> I'm not aware of a way to do this directly. However, you can subtract your Think Timer's Milliseconds Remaining from a Timer object that you create on your first Think call to get the time elapsed between moves.

wouldn't that be way too inaccurate?

**Comment by dudecon** [comment]
I agree that the timer for both players should be visible as part of the board state. It's not clear to me what the best way to implement that is. Perhaps copy the player TimeRemainingMs in to the board in a couple of new public int variables?

**Comment by dudecon** [comment]
Created a quick pull request. I chose to only store the opponent's time, since the active player's time is already available via `timer`.

**Comment by mcthouacbb** [comment]
Why is OpponentRemainingMs part of the board class? The board is for extracting properties of the chess state space, not for getting match and game information. Wouldn't it make more sense to make it part of the timer class?

**Comment by dudecon** [comment]
> Why is OpponentRemainingMs part of the board class? The board is for extracting properties of the chess state space, not for getting match and game information. Wouldn't it make more sense to make it part of the timer class?

Perhaps? I agree that if we're sticking with a physical metaphor of having a physical board and a physical timer, then the opponent's time going on the timer makes sense.

I thought putting it on the board made more sense because you might want to simulate the opponent's remaining time during move evaluation if you're trying a time-out strategy or something. In that case, the timer would be linked to board state, so it would make sense that they were tracked together.

As I said, it's not clear to me what the best way to implement this is. If it goes on the timer, do we keep a log on the timer of all of the turn evaluation durations? I could see a depth-sprint meta-attack being interesting if you note that your opponent isn't spending much time evaluating their moves. Or a time-out meta-attack by drawing the game out if the opponent spends the same amount of time every time.

In a broader sense, do we want to inform the bot about which bot they are playing against? Can the bots learn about their opponents and alter their strategy between matches? Or will the IChessBot object be re-instantiated for every match? It would be really interesting to get access to match history (including turn duration) for several previous matches so that the bot can "study" the opponent.

**Comment by SebLague** [comment]
Hi, I have added OpponentMillisecondsRemaining to the Timer.
